trigger:
- master

parameters:
- name: browser
  type: string
  default: chrome
  values:
  - chrome
  - edge
  - firefox

variables:
  buildConfiguration: Release

stages:
- stage: BuildAndInfo
  displayName: "Build + Info Stage"
  jobs:
  - job: DefaultJob
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Building in $(buildConfiguration) mode"
      displayName: 'Use variable'

    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
        echo This is environment variable: $(environment)
      displayName: 'Run a multi-line script'

    - script: |
        echo "Build ID: $(Build.BuildId)"
        echo "Build Number: $(Build.BuildNumber)"
        echo "Branch: $(Build.SourceBranch)"
        echo "Commit: $(Build.SourceVersion)"
        echo "Repo: $(Build.Repository.Name)"
        echo "Agent OS: $(Agent.OS)"
      displayName: "Print system variables"

    - script: echo "Browser selected = ${{ parameters.browser }}"
      displayName: "Print chosen browser"

    - script: mvn clean test -Dbrowser=${{ parameters.browser }}
      displayName: "Run TestNG tests with chosen browser"

- stage: CrossPlatform
  displayName: "Run on Multiple OS"
  jobs:
  - job: Linux
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Running on Linux with browser = ${{ parameters.browser }}"

  - job: Windows
    pool:
      vmImage: windows-latest
    steps:
    - script: echo "Running on Windows with browser = ${{ parameters.browser }}"
